create table if not exists public.site_visit_events (
  id bigint generated by default as identity primary key,
  visitor_id text not null,
  path text not null,
  route_type text not null default 'nav',
  route_value text not null default '',
  title text not null default '',
  referrer text not null default '',
  user_agent text not null default '',
  occurred_at timestamptz not null default now()
);

create index if not exists site_visit_events_occurred_at_idx
on public.site_visit_events (occurred_at desc);

create index if not exists site_visit_events_route_idx
on public.site_visit_events (route_type, occurred_at desc);

alter table public.site_visit_events enable row level security;

drop policy if exists "insert anonymous site visit events" on public.site_visit_events;
create policy "insert anonymous site visit events"
on public.site_visit_events
for insert
to anon, authenticated
with check (
  length(visitor_id) between 8 and 120
  and length(path) between 1 and 500
  and route_type in ('nav', 'blog', 'post', 'user')
  and length(route_value) <= 120
  and length(title) <= 160
  and length(referrer) <= 120
  and length(user_agent) <= 240
);

grant insert on table public.site_visit_events to anon, authenticated;
grant usage on sequence public.site_visit_events_id_seq to anon, authenticated;

-- 常用查看语句：
-- select date_trunc('day', occurred_at) as day, count(*) as views, count(distinct visitor_id) as visitors
-- from public.site_visit_events
-- group by day
-- order by day desc;
