import { mkdir, readdir, readFile, unlink, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import hljs from "highlight.js";
import { marked } from "marked";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.resolve(__dirname, "..");
export const postsContentDir = path.join(rootDir, "src", "content", "posts");
export const generatedPostsFile = path.join(rootDir, "src", "data", "posts.generated.js");

marked.setOptions({
  gfm: true,
  breaks: true,
});

marked.use({
  renderer: {
    code(token) {
      const language = String(token.lang || "").trim().toLowerCase();
      const code = String(token.text || "");
      const highlightedCode = highlightCode(code, language);
      const languageClass = language ? ` language-${escapeAttribute(language)}` : "";

      return `<pre class="article-code-block"><code class="hljs${languageClass}">${highlightedCode}</code></pre>`;
    },
  },
});

export async function loadPostsFromMarkdown() {
  await mkdir(postsContentDir, { recursive: true });
  const entries = await readdir(postsContentDir, { withFileTypes: true });
  const posts = [];

  for (const entry of entries) {
    if (!entry.isFile() || !entry.name.toLowerCase().endsWith(".md")) {
      continue;
    }

    const id = path.basename(entry.name, ".md");
    const source = await readFile(path.join(postsContentDir, entry.name), "utf8");
    posts.push(parsePostMarkdown(source, id));
  }

  return sortPosts(posts);
}

export function decoratePost(post) {
  const content = normalizeMarkdownContent(post.content);
  const blockCount = getMarkdownBlockCount(content);

  return {
    ...post,
    content,
    contentHtml: marked.parse(content).trim(),
    blockCount,
  };
}

export async function syncGeneratedPostsData() {
  const posts = await loadPostsFromMarkdown();
  const generated = posts.map((post) => decoratePost(post));
  const moduleSource = [
    "// This file is auto-generated by scripts/generate-posts-data.mjs.",
    "// Do not edit manually. Source files live in src/content/posts/*.md.",
    `export const posts = ${JSON.stringify(generated, null, 2)};`,
    "",
  ].join("\n");

  await writeFile(generatedPostsFile, moduleSource, "utf8");
  return generated;
}

export async function writePostsToMarkdown(posts) {
  await mkdir(postsContentDir, { recursive: true });
  const existingEntries = await readdir(postsContentDir, { withFileTypes: true });
  const existingFiles = new Set(
    existingEntries
      .filter((entry) => entry.isFile() && entry.name.toLowerCase().endsWith(".md"))
      .map((entry) => entry.name),
  );
  const nextFiles = new Set();

  for (const post of sortPosts(posts)) {
    const fileName = `${post.id}.md`;
    nextFiles.add(fileName);
    await writeFile(path.join(postsContentDir, fileName), serializePostMarkdown(post), "utf8");
  }

  for (const fileName of existingFiles) {
    if (!nextFiles.has(fileName)) {
      await unlink(path.join(postsContentDir, fileName));
    }
  }

  return await syncGeneratedPostsData();
}

export function normalizeMarkdownContent(value) {
  return String(value || "")
    .replace(/\r\n/g, "\n")
    .replace(/\r/g, "\n")
    .trim();
}

function parsePostMarkdown(source, id) {
  const normalizedSource = String(source || "").replace(/\r\n/g, "\n").replace(/\r/g, "\n");
  const match = normalizedSource.match(/^---\n([\s\S]*?)\n---\n?([\s\S]*)$/);

  if (!match) {
    throw new Error(`${id}.md 缺少 front matter`);
  }

  const metadata = parseFrontMatter(match[1], id);
  const content = normalizeMarkdownContent(match[2]);

  return {
    id,
    ...metadata,
    content,
  };
}

function parseFrontMatter(block, id) {
  const metadata = {
    title: "",
    summary: "",
    publishedAt: "",
    tags: [],
  };
  const lines = String(block || "").split("\n");

  for (let index = 0; index < lines.length; index += 1) {
    const line = lines[index].trimEnd();
    if (!line.trim()) {
      continue;
    }

    if (/^tags\s*:\s*$/.test(line)) {
      const tags = [];
      while (index + 1 < lines.length && /^\s*-\s+/.test(lines[index + 1])) {
        index += 1;
        tags.push(parseScalar(lines[index].replace(/^\s*-\s+/, "")));
      }
      metadata.tags = tags.filter(Boolean);
      continue;
    }

    const scalarMatch = line.match(/^([A-Za-z][A-Za-z0-9_-]*)\s*:\s*(.*)$/);
    if (!scalarMatch) {
      throw new Error(`${id}.md front matter 无法解析：${line}`);
    }

    const [, key, value] = scalarMatch;
    if (!(key in metadata)) {
      continue;
    }

    metadata[key] = parseScalar(value);
  }

  return metadata;
}

function parseScalar(value) {
  const text = String(value || "").trim();
  if (!text) {
    return "";
  }

  if ((text.startsWith("\"") && text.endsWith("\"")) || (text.startsWith("'") && text.endsWith("'"))) {
    try {
      return JSON.parse(text.startsWith("'") ? `"${text.slice(1, -1).replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"` : text);
    } catch {
      return text.slice(1, -1);
    }
  }

  return text;
}

function serializePostMarkdown(post) {
  const tags = Array.isArray(post.tags) ? post.tags : [];
  const content = normalizeMarkdownContent(post.content);

  return [
    "---",
    `title: ${JSON.stringify(String(post.title || "").trim())}`,
    `summary: ${JSON.stringify(String(post.summary || "").trim())}`,
    `publishedAt: ${JSON.stringify(String(post.publishedAt || "").trim())}`,
    "tags:",
    ...tags.map((tag) => `  - ${JSON.stringify(String(tag || "").trim())}`),
    "---",
    "",
    content,
    "",
  ].join("\n");
}

function sortPosts(posts) {
  return [...posts].sort((left, right) => new Date(right.publishedAt).getTime() - new Date(left.publishedAt).getTime());
}

function getMarkdownBlockCount(content) {
  return normalizeMarkdownContent(content)
    .split(/\n\s*\n/g)
    .map((block) => block.trim())
    .filter(Boolean)
    .length;
}

function highlightCode(code, language) {
  if (language && hljs.getLanguage(language)) {
    return hljs.highlight(code, { language }).value;
  }

  return hljs.highlightAuto(code).value;
}

function escapeAttribute(value) {
  return String(value || "")
    .replace(/&/g, "&amp;")
    .replace(/"/g, "&quot;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
}
