import { mkdir, readdir, readFile, unlink, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import hljs from "highlight.js";
import { Marked } from "marked";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.resolve(__dirname, "..");
export const postsContentDir = path.join(rootDir, "src", "content", "posts");
export const generatedPostsFile = path.join(rootDir, "src", "data", "posts.generated.js");
export const postImageDir = path.join(rootDir, "public", "post-image");
const POST_IMAGE_PATTERN = /\/post-image\/([^)\s>"']+)/g;

export async function loadPostsFromMarkdown() {
  await mkdir(postsContentDir, { recursive: true });
  const entries = await readdir(postsContentDir, { withFileTypes: true });
  const posts = [];

  for (const entry of entries) {
    if (!entry.isFile() || !entry.name.toLowerCase().endsWith(".md")) {
      continue;
    }

    const id = path.basename(entry.name, ".md");
    const source = await readFile(path.join(postsContentDir, entry.name), "utf8");
    posts.push(parsePostMarkdown(source, id));
  }

  return sortPosts(posts);
}

export function decoratePost(post) {
  const content = normalizeMarkdownContent(post.content);
  const blockCount = getMarkdownBlockCount(content);
  const { html, toc } = renderMarkdown(content);

  return {
    ...post,
    content,
    contentHtml: html,
    blockCount,
    toc,
  };
}

export async function syncGeneratedPostsData() {
  const posts = await loadPostsFromMarkdown();
  const generated = posts.map((post) => decoratePost(post));
  const moduleSource = [
    "// This file is auto-generated by scripts/generate-posts-data.mjs.",
    "// Do not edit manually. Source files live in src/content/posts/*.md.",
    `export const posts = ${JSON.stringify(generated, null, 2)};`,
    "",
  ].join("\n");

  await writeFile(generatedPostsFile, moduleSource, "utf8");
  return generated;
}

export async function writePostsToMarkdown(posts) {
  await mkdir(postsContentDir, { recursive: true });
  const existingEntries = await readdir(postsContentDir, { withFileTypes: true });
  const existingFiles = new Set(
    existingEntries
      .filter((entry) => entry.isFile() && entry.name.toLowerCase().endsWith(".md"))
      .map((entry) => entry.name),
  );
  const existingPosts = await loadPostsFromMarkdown();
  const removedPostIds = new Set(existingPosts.map((post) => post.id));
  const nextFiles = new Set();
  const nextPosts = sortPosts(posts);

  for (const post of nextPosts) {
    const fileName = `${post.id}.md`;
    nextFiles.add(fileName);
    removedPostIds.delete(post.id);
    await writeFile(path.join(postsContentDir, fileName), serializePostMarkdown(post), "utf8");
  }

  for (const fileName of existingFiles) {
    if (!nextFiles.has(fileName)) {
      await unlink(path.join(postsContentDir, fileName));
    }
  }

  await deleteUnusedPostImages(existingPosts, nextPosts, removedPostIds);

  return await syncGeneratedPostsData();
}

export function normalizeMarkdownContent(value) {
  return String(value || "")
    .replace(/\r\n/g, "\n")
    .replace(/\r/g, "\n")
    .trim();
}

export function getReferencedPostImageNames(content) {
  const matches = String(content || "").matchAll(POST_IMAGE_PATTERN);
  return Array.from(new Set(
    [...matches]
      .map((match) => String(match[1] || "").trim())
      .filter(Boolean),
  ));
}

function parsePostMarkdown(source, id) {
  const normalizedSource = String(source || "").replace(/\r\n/g, "\n").replace(/\r/g, "\n");
  const match = normalizedSource.match(/^---\n([\s\S]*?)\n---\n?([\s\S]*)$/);

  if (!match) {
    throw new Error(`${id}.md 缺少 front matter`);
  }

  const metadata = parseFrontMatter(match[1], id);
  const content = normalizeMarkdownContent(match[2]);

  return {
    id,
    ...metadata,
    content,
  };
}

function parseFrontMatter(block, id) {
  const metadata = {
    title: "",
    summary: "",
    publishedAt: "",
    tags: [],
  };
  const lines = String(block || "").split("\n");

  for (let index = 0; index < lines.length; index += 1) {
    const line = lines[index].trimEnd();
    if (!line.trim()) {
      continue;
    }

    if (/^tags\s*:\s*$/.test(line)) {
      const tags = [];
      while (index + 1 < lines.length && /^\s*-\s+/.test(lines[index + 1])) {
        index += 1;
        tags.push(parseScalar(lines[index].replace(/^\s*-\s+/, "")));
      }
      metadata.tags = tags.filter(Boolean);
      continue;
    }

    const scalarMatch = line.match(/^([A-Za-z][A-Za-z0-9_-]*)\s*:\s*(.*)$/);
    if (!scalarMatch) {
      throw new Error(`${id}.md front matter 无法解析：${line}`);
    }

    const [, key, value] = scalarMatch;
    if (!(key in metadata)) {
      continue;
    }

    metadata[key] = parseScalar(value);
  }

  return metadata;
}

function parseScalar(value) {
  const text = String(value || "").trim();
  if (!text) {
    return "";
  }

  if ((text.startsWith("\"") && text.endsWith("\"")) || (text.startsWith("'") && text.endsWith("'"))) {
    try {
      return JSON.parse(text.startsWith("'") ? `"${text.slice(1, -1).replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"` : text);
    } catch {
      return text.slice(1, -1);
    }
  }

  return text;
}

function serializePostMarkdown(post) {
  const tags = Array.isArray(post.tags) ? post.tags : [];
  const content = normalizeMarkdownContent(post.content);

  return [
    "---",
    `title: ${JSON.stringify(String(post.title || "").trim())}`,
    `summary: ${JSON.stringify(String(post.summary || "").trim())}`,
    `publishedAt: ${JSON.stringify(String(post.publishedAt || "").trim())}`,
    "tags:",
    ...tags.map((tag) => `  - ${JSON.stringify(String(tag || "").trim())}`),
    "---",
    "",
    content,
    "",
  ].join("\n");
}

async function deleteUnusedPostImages(existingPosts, nextPosts, removedPostIds) {
  if (removedPostIds.size === 0) {
    return;
  }

  const remainingImageNames = new Set(
    nextPosts.flatMap((post) => getReferencedPostImageNames(post.content)),
  );
  const removableImageNames = new Set();

  for (const post of existingPosts) {
    if (!removedPostIds.has(post.id)) {
      continue;
    }

    for (const imageName of getReferencedPostImageNames(post.content)) {
      if (!remainingImageNames.has(imageName)) {
        removableImageNames.add(imageName);
      }
    }
  }

  await Promise.all(
    [...removableImageNames].map(async (imageName) => {
      const filePath = path.join(postImageDir, imageName);
      try {
        await unlink(filePath);
      } catch (error) {
        if (error && typeof error === "object" && "code" in error && error.code === "ENOENT") {
          return;
        }
        throw error;
      }
    }),
  );
}

function sortPosts(posts) {
  return [...posts].sort((left, right) => new Date(right.publishedAt).getTime() - new Date(left.publishedAt).getTime());
}

function getMarkdownBlockCount(content) {
  return normalizeMarkdownContent(content)
    .split(/\n\s*\n/g)
    .map((block) => block.trim())
    .filter(Boolean)
    .length;
}

function renderMarkdown(content) {
  const toc = [];
  const headingIds = new Map();
  const parser = new Marked({
    gfm: true,
    breaks: true,
  });

  parser.use({
    renderer: {
      code(token) {
        const language = String(token.lang || "").trim().toLowerCase();
        const code = String(token.text || "");
        const highlightedCode = highlightCode(code, language);
        const languageClass = language ? ` language-${escapeAttribute(language)}` : "";

        return `<pre class="article-code-block"><code class="hljs${languageClass}">${highlightedCode}</code></pre>`;
      },
      heading(token) {
        const depth = Number(token.depth || 0);
        const rawText = String(token.text || "").trim();
        const text = rawText.replace(/<[^>]+>/g, "").trim();
        const id = createHeadingId(text, headingIds);
        const inlineHtml = this.parser.parseInline(token.tokens);

        if (depth >= 2 && depth <= 4 && text) {
          toc.push({ id, text, depth });
        }

        return `<h${depth} id="${escapeAttribute(id)}">${inlineHtml}</h${depth}>`;
      },
    },
  });

  return {
    html: parser.parse(content).trim(),
    toc,
  };
}

function highlightCode(code, language) {
  if (language && hljs.getLanguage(language)) {
    return hljs.highlight(code, { language }).value;
  }

  return hljs.highlightAuto(code).value;
}

function escapeAttribute(value) {
  return String(value || "")
    .replace(/&/g, "&amp;")
    .replace(/"/g, "&quot;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
}

function createHeadingId(text, usedIds) {
  const baseId = slugifyHeading(text) || "section";
  const currentCount = usedIds.get(baseId) || 0;
  const nextCount = currentCount + 1;
  usedIds.set(baseId, nextCount);
  return currentCount === 0 ? baseId : `${baseId}-${nextCount}`;
}

function slugifyHeading(value) {
  return String(value || "")
    .toLowerCase()
    .replace(/[^\w\u4e00-\u9fff\s-]/g, "")
    .trim()
    .replace(/[\s_-]+/g, "-")
    .replace(/^-+|-+$/g, "");
}
